### ISSUE TITLE
GridBundle requires MakerBundle in prod

### ISSUE THREAD

**Issue by aleho** [Sylius/SyliusGridBundle#250]
Recently `composer install --no-dev` fails on production environments:

```
Script cache:clear --no-warmup returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Class "Symfony\Bundle\MakerBundle\Maker\AbstractMaker" not found in /application/vendor/sylius/grid-bundle/src/Bundle/Maker/MakeGrid.php:29
!!  Stack trace:
!!  #0 /application/vendor/composer/ClassLoader.php(571): include()
!!  #1 /application/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
!!  #2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
!!  #3 /application/src/Filtering/GroupFilterPass.php(22): is_subclass_of()
!!  #4 /application/vendor/symfony/dependency-injection/Compiler/Compiler.php(82): App\Filtering\GroupFilterPass->process()
!!  #5 /application/vendor/symfony/dependency-injection/ContainerBuilder.php(757): Symfony\Component\DependencyInjection\Compiler\Compiler->compile()
!!  #6 /application/vendor/symfony/http-kernel/Kernel.php(546): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
!!  #7 /application/vendor/symfony/http-kernel/Kernel.php(787): Symfony\Component\HttpKernel\Kernel->initializeContainer()
!!  #8 /application/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
!!  #9 /application/vendor/symfony/framework-bundle/Console/Application.php(168): Symfony\Component\HttpKernel\Kernel->boot()
!!  #10 /application/vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #11 /application/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
!!  #12 /application/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(54): Symfony\Component\Console\Application->run()
!!  #13 /application/vendor/autoload_runtime.php(35): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
!!  #14 /application/bin/console(11): require_once('...')
!!  #15 {main}
!!    thrown in /application/vendor/sylius/grid-bundle/src/Bundle/Maker/MakeGrid.php on line 29
!!  
Script @auto-scripts was called via post-install-cmd
```

This should not be a requirement for production deployments.

**Comment by dannyvw** [comment]
Caused by https://github.com/Sylius/SyliusGridBundle/pull/206
